### ISSUE TITLE
Feature Request: Have pointless update to show the current branch.

### ISSUE THREAD

**Issue by KyleTryon** [felicianotech/pointless#49]
**Current behavior:**
Pointless currently shows the status of and links to the default/master branch.

**Desired behavior:**
Pointless status and link should reflect the current branch being viewed in GitHub.

**Comment by felicianotech** [comment]
I assume this is referring to when you're viewing the "code" tab? What about the other tabs such as Issues, PR, GitHub Actions, etc? Just default to showing the default branch?

**Comment by KyleTryon** [comment]
That is correct. 

For example: https://github.com/felicianotech/pointless/tree/create-project-db

I believe on issues and such I would want to see the master branch. However, on PRs I think it would again be great to show the "branch" status for that PR.

**Comment by felicianotech** [comment]
For PRs, the PR itself is already showing the branch status, more specifically the "head" branch status. I'm thinking it should show the "base" branch status.

Currently, since `master` is typically the base branch, I use the status dot at the top to know when I can merge a PR when I don't want two PRs to be merged at the same time in case they overtake each other on deploy and mess something up.

**Comment by felicianotech** [comment]
@KyleTryon Your request has been implemented and is available in Pointless v2005.1. You'll get it when:

1. Google approves the release.
2. Your browser updates the extension, which I think happens at least once a day.
